/**
 * 
 */
package education;

import java.util.*;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Facultative
//  @ File Name : Archive.java
//  @ Date : 29.03.2011
//  @ Author : 
//
//

public class Archive {
	private List<Course> courses;
	private static Archive instance;
	
	private Archive(){
		this.courses = new ArrayList<Course>();
	}
	
	public void saveCourse(Course course) {
		this.courses.add(course);
	}
	
	public List<Course> getCourses(){
		return courses;
	}
	
	public static Archive Instance() {
		if (instance == null)
			instance = new Archive();
		return instance;
	}
}

