/**
 * 
 */
package education;

import java.util.*;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Facultative
//  @ File Name : Course.java
//  @ Date : 29.03.2011
//  @ Author : 
//
//

public class Course {
	private String subjectName;
	private List<Teacher> teachers;
	private List<Student> students;
	private Map<Student, Integer> marks;
	private boolean registration;
	private boolean studying;
	private int maxListenersCount;
	public Course(String subjectName, int maxListenersCount){
		this.subjectName = subjectName;
		this.maxListenersCount = maxListenersCount;
		this.registration = true;
		this.studying = false;
		this.teachers = new ArrayList<Teacher>();
		this.students = new ArrayList<Student>();
		this.marks = new HashMap<Student, Integer>();
	}
		
	/**
	 * @return the maxListenersCount
	 */
	public int getMaxListenersCount() {
		return maxListenersCount;
	}

	/**
	 * @param maxListenersCount the maxListenersCount to set
	 */
	public void setMaxListenersCount(int maxListenersCount) {
		this.maxListenersCount = maxListenersCount;
	}

	/**
	 * @return the subjectName
	 */
	public String getSubjectName() {
		return subjectName;
	}

	/**
	 * @return the registration
	 */
	public boolean isRegistration() {
		return registration;
	}

	/**
	 * @return the studying
	 */
	public boolean isStudying() {
		return studying;
	}

	public void addTeacher(Teacher teacher) {
		teachers.add(teacher);
	}
	
	public void removeTeacher(Teacher teacher) {
		teachers.remove(teacher);
	}
	
	public boolean addStudent(Student student) {
		if (registration && students.size() < maxListenersCount){
			students.add(student);
			return true;
		}else
			return false;
	}
	
	public void removeStudent(Student student) {
		students.remove(student);
	}
	
	public void setMark(Student student, Integer mark) {
		marks.put(student, mark);
	}
	
	public int getMark(Student student) {
		return marks.get(student);
	}
	
	public List<Teacher> getTeachers() {
		return teachers;
	}
	
	public List<Student> getStudents() {
		return students;
	}
	
	public Map<Student, Integer> getMarks() {
		return marks;
	}
	
	public void studying() {
		this.registration = false;
		this.studying = true;
	}
	
	public void endCourse(){
		this.studying = false;
	}
}

