/**
 * 
 */
package education;

import java.util.*;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Facultative
//  @ File Name : Teacher.java
//  @ Date : 29.03.2011
//  @ Author : 
//
//

public class Teacher {
	private String name;
	private List<Course> courses;
	
	public Teacher(String name){
		this.name = name;
	}
	
	/**
	 * @return the name
	 */
	public String getName() {
		return name;
	}

	/**
	 * @return the courses
	 */
	public List<Course> getCourses() {
		return courses;
	}

	public void declareCourseRegistration(Course course, int maxListenersCount) {
		if (courses == null)
			courses = new ArrayList<Course>();
		course.setMaxListenersCount(maxListenersCount);
		courses.add(course);
		course.addTeacher(this);
	}
	
	public void addCourse(Course course){
		if (courses == null)
			courses = new ArrayList<Course>();
		courses.add(course);
		course.addTeacher(this);
	}
	
	public boolean register(Student student, Course course) {
		return course.addStudent(student);
	}
	
	public boolean study(Course course){
		if (courses.contains(course)){
			course.studying();
			return true;
		}
		else
			return false;
	}
	
	public void setMarks() {
		Random rnd = new Random();
		for (Course course : courses)
			for (Student student : course.getStudents())
				course.setMark(student, rnd.nextInt(11));
	}
	
	public void setMarks(Course course){
		Random rnd = new Random();
		for (Student student : course.getStudents())
			course.setMark(student, rnd.nextInt(11));
	}
	
	public void saveToArchive(Course course) {
		course.endCourse();
		Archive.Instance().saveCourse(course);
		endCourse(course);
	}
	
	public void endCourse(Course course) {
		if (courses != null && courses.contains(course)){
			for (Student student : course.getStudents())
				student.endCourse(course);
			this.courses.remove(course);
		}
	}
}

