// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package voting.domain;

import java.lang.String;

privileged aspect Category_Roo_ToString {
    
    public String Category.toString() {
    	return getName();
    }
    
}
