// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package voting.domain;

import java.util.List;
import java.util.Random;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import voting.domain.Answer;
import voting.domain.QuestionDataOnDemand;

privileged aspect AnswerDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AnswerDataOnDemand: @Component;
    
    private Random AnswerDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Answer> AnswerDataOnDemand.data;
    
    @Autowired
    private QuestionDataOnDemand AnswerDataOnDemand.questionDataOnDemand;
    
    public Answer AnswerDataOnDemand.getNewTransientAnswer(int index) {
        voting.domain.Answer obj = new voting.domain.Answer();
        setText(obj, index);
        setQuestion(obj, index);
        return obj;
    }
    
    private void AnswerDataOnDemand.setText(Answer obj, int index) {
        java.lang.String text = "text_" + index;
        obj.setText(text);
    }
    
    private void AnswerDataOnDemand.setQuestion(Answer obj, int index) {
        voting.domain.Question question = questionDataOnDemand.getRandomQuestion();
        obj.setQuestion(question);
    }
    
    public Answer AnswerDataOnDemand.getSpecificAnswer(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Answer obj = data.get(index);
        return Answer.findAnswer(obj.getId());
    }
    
    public Answer AnswerDataOnDemand.getRandomAnswer() {
        init();
        Answer obj = data.get(rnd.nextInt(data.size()));
        return Answer.findAnswer(obj.getId());
    }
    
    public boolean AnswerDataOnDemand.modifyAnswer(Answer obj) {
        return false;
    }
    
    public void AnswerDataOnDemand.init() {
        data = voting.domain.Answer.findAnswerEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Answer' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<voting.domain.Answer>();
        for (int i = 0; i < 10; i++) {
            voting.domain.Answer obj = getNewTransientAnswer(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
