//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Auto.java
//  @ Date : 25.03.2011
//  @ Author : 
//
//




public class Auto
{
	
 

	public static void auto(String name, int price ){
		System.out.println("auto "+ name+"; auto's hire per day "+ price+"$");
					}
	
	public static void price(int period, int price){
		
		 price*= period;
		
		System.out.println("sum price for hiring "+ price+"$");
			}
}
