//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.java
//  @ Date : 25.03.2011
//  @ Author : 
//
//




public class Client
{
	private String name;
	private  String passport;
	 
			
			public Client(String na, String pa) {
				name = na;
				passport = pa;
			}
			public String getNa() {
				return name;
			}
			public String getPa() {
				return passport;
			}
			public void identity() {
				
				System.out.println("client "+ name+"; client's passport data: "+ passport);
			}
		

			public int choice(){
				int n= (int) ((Math.random() * 10)/4)+1	;
				System.out.println("client "+name+"choise "+ n);
				return n;
				
			}
			
			public boolean pay(boolean y){
				if (y==true){
					System.out.println("client "+ name+" has payed");
				}
				else System.out.println("client "+ name+" hasn't payed");
				return y;
				
			}
public void using() {
				
				System.out.println("client "+ name+" took auto,has used auto, has returned auto");
			}
	 
public boolean damage(boolean y){
	if (y==true){
		System.out.println("client "+ name+" has damaged auto");
	}
	return y;
	
}
}
