//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Damage.java
//  @ Date : 25.03.2011
//  @ Author : 
//
//




public class Damage
{
	public boolean damage ;
}


