
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Order.java
//  @ Date : 25.03.2011
//  @ Author : 
//
//




public class Order
{
	private int days;
	public Order(int da) {
		days = da;
		}
	public int getDa() {
		return days;
	}
	
	public void ordering() {
		
		System.out.println(days + " days");
	}	
	public  boolean payed;
		public static void order(int number,int period){
			      
			 System.out.println("order's number "+ number+"; hiring period days "+ period);
			}
	
	
}
